[gemometry]
vertices = [
    [21, 0],
    [45, 0],
    [45, 25],
    [20, 25],

    [0, 45],
    [65, 45],

    [20, 85],
    [45, 85],

    [20, 110],
    [45, 110],

    [0, 75],
    [0, 95],
    [0, 100],
    
    [65, 75],
    [65, 95],
    [65, 100],

    [20, 150],
    [20, 180],
    [20, 190],
    
    [45, 150],
    [45, 180],
    [45, 190]
]
edges = [
    [0, 1],
    [1, 2],
    [2, 3],
    [3, 0],
    [0, 2],
    [1, 3],

    [2, 5],
    [3, 4],
    [3, 5],
    [2, 4],
    [4, 5],

    [5, 7],
    [4, 6],
    [4, 7],
    [5, 6],
    [6, 7],

    [7, 9],
    [6, 8],
    [6, 9],
    [7, 8],
    [8, 9],

    [4, 10],
    [10, 11],
    [11, 12],

    [5, 13],
    [13, 14],
    [14, 15],

    [8, 16],
    [16, 17],
    [17, 18],

    [9, 19],
    [19, 20],
    [20, 21]
]